BEGIN;

CREATE TEMP TABLE debtors_migration AS
SELECT
    row_number() OVER (ORDER BY full_name ASC, id ASC)::BIGINT AS new_id,
    full_name,
    first_name,
    last_name,
    borrowed,
    repaid,
    remaining,
    photo_url,
    created_at,
    updated_at,
    id AS old_id
FROM public.debtors;

CREATE TEMP TABLE loans_migration AS
SELECT
    row_number() OVER (ORDER BY loan_date ASC NULLS LAST, id ASC)::BIGINT AS new_id,
    debtor_map.new_id AS new_debtor_id,
    loans.amount,
    loans.loan_date,
    loans.due_date,
    loans.notes,
    loans.created_at,
    loans.updated_at
FROM public.loans
JOIN debtors_migration AS debtor_map ON debtor_map.old_id = loans.debtor_id;

CREATE TEMP TABLE repayments_migration AS
SELECT
    row_number() OVER (ORDER BY repayment_date ASC NULLS LAST, id ASC)::BIGINT AS new_id,
    debtor_map.new_id AS new_debtor_id,
    repayments.amount,
    repayments.repayment_date,
    repayments.created_at,
    repayments.updated_at
FROM public.repayments
JOIN debtors_migration AS debtor_map ON debtor_map.old_id = repayments.debtor_id;

DROP TABLE IF EXISTS public.repayments;
DROP TABLE IF EXISTS public.loans;
DROP TABLE IF EXISTS public.debtors;

CREATE TABLE public.debtors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    borrowed NUMERIC(12, 2) NOT NULL DEFAULT 0,
    repaid NUMERIC(12, 2) NOT NULL DEFAULT 0,
    remaining NUMERIC(12, 2) NOT NULL DEFAULT 0,
    photo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_id BIGINT NOT NULL REFERENCES public.debtors(id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    loan_date DATE,
    due_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.repayments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_id BIGINT NOT NULL REFERENCES public.debtors(id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    repayment_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.debtors (
    id, full_name, first_name, last_name, borrowed, repaid, remaining, photo_url, created_at, updated_at
)
SELECT new_id, full_name, first_name, last_name, borrowed, repaid, remaining, photo_url, created_at, updated_at
FROM debtors_migration
ORDER BY new_id;

INSERT INTO public.loans (
    id, debtor_id, amount, loan_date, due_date, notes, created_at, updated_at
)
SELECT new_id, new_debtor_id, amount, loan_date, due_date, notes, created_at, updated_at
FROM loans_migration
ORDER BY new_id;

INSERT INTO public.repayments (
    id, debtor_id, amount, repayment_date, created_at, updated_at
)
SELECT new_id, new_debtor_id, amount, repayment_date, created_at, updated_at
FROM repayments_migration
ORDER BY new_id;

SELECT setval(pg_get_serial_sequence('public.debtors', 'id'), COALESCE(MAX(id), 0) + 1, false)
FROM public.debtors;
SELECT setval(pg_get_serial_sequence('public.loans', 'id'), COALESCE(MAX(id), 0) + 1, false)
FROM public.loans;
SELECT setval(pg_get_serial_sequence('public.repayments', 'id'), COALESCE(MAX(id), 0) + 1, false)
FROM public.repayments;

CREATE INDEX loans_debtor_id_idx ON public.loans(debtor_id);
CREATE INDEX repayments_debtor_id_idx ON public.repayments(debtor_id);
CREATE INDEX loans_loan_date_idx ON public.loans(loan_date);
CREATE INDEX repayments_repayment_date_idx ON public.repayments(repayment_date);

ALTER TABLE public.debtors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repayments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read debtors"
    ON public.debtors
    FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Public read loans"
    ON public.loans
    FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Public read repayments"
    ON public.repayments
    FOR SELECT
    TO anon, authenticated
    USING (true);

COMMIT;
